/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
typedef unsigned volatile int vuint32_t;
#include <stdint.h>

//RCC
#define RCC_BASE   0x40021000
#define RCC_APB *((vuint32_t *)(RCC_BASE + 0x18))
#define RCC_IOPAEN (1<<2)

//GPIOA
#define GPIOA_BASE 0x40010800
#define GPIOA_CRH *((vuint32_t *)(GPIOA_BASE + 0x04))
#define GPIO_ODR  *((vuint32_t *)(GPIOA_BASE + 0x0C))
#define GPIOA_CRL *((vuint32_t *)(GPIOA_BASE + 0x00))

//EXTI0
#define EXTI_BASE  0x40010400
#define EXTI_IMR   *((vuint32_t *)(EXTI_BASE + 0x00))
#define EXTI_RTSR   *((vuint32_t *)(EXTI_BASE + 0x08))
#define EXTI_PR    *((vuint32_t *)(EXTI_BASE + 0x14))

//AFIO
#define AFIO_BASE  0x40010000
#define AFIO_EXTICR1   *((vuint32_t *)(AFIO_BASE + 0x08))

//NVIC
#define NVIC_EXTIR0   *((vuint32_t *)(0xE000E100))

void clock_init()
{
	RCC_APB |= RCC_IOPAEN;
	//alternative function clock enable
	RCC_APB |= (1 << 0);
}
void GPIO_init()
{
	// pin 13 in port A is output
	GPIOA_CRH &= 0xFF0FFFFF;
	GPIOA_CRH |= 0x00200000;

	//pin A0 input floating
	GPIOA_CRL |= (1 << 2);


}

void EXTI0_IRQHandler (void)
{
	// interrupt occured >> EXTI0 >> PORA pin 0 rising edge
	// toggle led Pin A13
	GPIO_ODR ^= (1 << 13);

	//clear pending request for line 0
	EXTI_PR |= (1 << 0);
}
int main(void)
{
	clock_init();
	GPIO_init();
	//
	AFIO_EXTICR1 |= (0000 << 0);

	//rising edge enable
	EXTI_RTSR |= (1 << 0);

	//Enable EXTI0
	EXTI_IMR  |= (1 << 0);

	//enable NVIV IRQ6 EXTR line 0
	NVIC_EXTIR0 |= (1 << 6);


	while(1);
}
